/**
 * NEXUS CODEX HARNESS - TYPES & CONSTANTS (Phase 1 Foundation)
 * Defines core lifecycle states, item types, event types, and ID helpers.
 */

const crypto = require('crypto');

const THREAD_STATUS = Object.freeze({
  CREATED: 'CREATED',
  ACTIVE: 'ACTIVE',
  ARCHIVED: 'ARCHIVED',
});

const TURN_STATUS = Object.freeze({
  CREATED: 'CREATED',
  RUNNING: 'RUNNING',
  WAITING_FOR_APPROVAL: 'WAITING_FOR_APPROVAL',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

const ITEM_STATUS = Object.freeze({
  STARTED: 'STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

const ITEM_TYPES = Object.freeze({
  USER_MESSAGE: 'USER_MESSAGE',
  AGENT_MESSAGE: 'AGENT_MESSAGE',
  PLAN: 'PLAN',
  TOOL_CALL: 'TOOL_CALL',
  TOOL_RESULT: 'TOOL_RESULT',
  FILE_CHANGE: 'FILE_CHANGE',
  CHANGE_SET: 'CHANGE_SET',
  APPROVAL_REQUEST: 'APPROVAL_REQUEST',
  SUBAGENT_DELEGATION: 'SUBAGENT_DELEGATION',
  SUBAGENT_RESULT: 'SUBAGENT_RESULT',
  ERROR: 'ERROR',
});

const CHANGESET_STATUS = Object.freeze({
  PROPOSED: 'PROPOSED',
  EVALUATING: 'EVALUATING',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVED: 'APPROVED',
  APPLIED: 'APPLIED',
  REJECTED: 'REJECTED',
  ROLLED_BACK: 'ROLLED_BACK',
  FAILED: 'FAILED',
  VERIFIED: 'VERIFIED',
});

const HANDOFF_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  CONSUMED: 'CONSUMED',
  SUPERSEDED: 'SUPERSEDED',
  ARCHIVED: 'ARCHIVED',
});

const EVENT_TYPES = Object.freeze({
  THREAD_CREATED: 'THREAD_CREATED',
  THREAD_UPDATED: 'THREAD_UPDATED',
  THREAD_ARCHIVED: 'THREAD_ARCHIVED',
  TURN_STARTED: 'TURN_STARTED',
  TURN_UPDATED: 'TURN_UPDATED',
  TURN_COMPLETED: 'TURN_COMPLETED',
  TURN_FAILED: 'TURN_FAILED',
  TURN_CANCELLED: 'TURN_CANCELLED',
  ITEM_STARTED: 'ITEM_STARTED',
  ITEM_UPDATED: 'ITEM_UPDATED',
  ITEM_COMPLETED: 'ITEM_COMPLETED',
  ITEM_FAILED: 'ITEM_FAILED',
  ITEM_CANCELLED: 'ITEM_CANCELLED',
  CHANGE_SET_CREATED: 'CHANGE_SET_CREATED',
  CHANGE_SET_EVALUATING: 'CHANGE_SET_EVALUATING',
  CHANGE_SET_APPROVAL_REQUIRED: 'CHANGE_SET_APPROVAL_REQUIRED',
  CHANGE_SET_APPROVED: 'CHANGE_SET_APPROVED',
  CHANGE_SET_APPLIED: 'CHANGE_SET_APPLIED',
  CHANGE_SET_ROLLED_BACK: 'CHANGE_SET_ROLLED_BACK',
  CHANGE_SET_VERIFIED: 'CHANGE_SET_VERIFIED',
  CHANGE_SET_FAILED: 'CHANGE_SET_FAILED',
  HANDOFF_CREATED: 'HANDOFF_CREATED',
  HANDOFF_RESTORED: 'HANDOFF_RESTORED',
  HANDOFF_CONSUMED: 'HANDOFF_CONSUMED',
  SUBAGENT_CREATED: 'SUBAGENT_CREATED',
  SUBAGENT_STARTED: 'SUBAGENT_STARTED',
  SUBAGENT_WAITING: 'SUBAGENT_WAITING',
  SUBAGENT_COMPLETED: 'SUBAGENT_COMPLETED',
  SUBAGENT_FAILED: 'SUBAGENT_FAILED',
  SUBAGENT_CANCELLED: 'SUBAGENT_CANCELLED',
  SUBAGENT_RESULT: 'SUBAGENT_RESULT',
  CHILD_WORKSPACE_CREATED: 'CHILD_WORKSPACE_CREATED',
  CHILD_WORKSPACE_READY: 'CHILD_WORKSPACE_READY',
  CHILD_WORKSPACE_CLEANUP_STARTED: 'CHILD_WORKSPACE_CLEANUP_STARTED',
  CHILD_WORKSPACE_CLEANED: 'CHILD_WORKSPACE_CLEANED',
  CHILD_WORKSPACE_ADOPTION_STARTED: 'CHILD_WORKSPACE_ADOPTION_STARTED',
  CHILD_WORKSPACE_ADOPTED: 'CHILD_WORKSPACE_ADOPTED',
  CHILD_WORKSPACE_ADOPTION_FAILED: 'CHILD_WORKSPACE_ADOPTION_FAILED',
  WORKER_STARTED: 'WORKER_STARTED',
  WORKER_ERROR: 'WORKER_ERROR',
  WORKER_EXITED: 'WORKER_EXITED',
  SUBAGENT_PROGRESS: 'SUBAGENT_PROGRESS',
  SWARM_CREATED: 'SWARM_CREATED',
  SWARM_STARTED: 'SWARM_STARTED',
  SWARM_TASK_QUEUED: 'SWARM_TASK_QUEUED',
  SWARM_TASK_STARTED: 'SWARM_TASK_STARTED',
  SWARM_TASK_COMPLETED: 'SWARM_TASK_COMPLETED',
  SWARM_TASK_FAILED: 'SWARM_TASK_FAILED',
  SWARM_TASK_CANCELLED: 'SWARM_TASK_CANCELLED',
  SWARM_CONFLICT_DETECTED: 'SWARM_CONFLICT_DETECTED',
  SWARM_AGGREGATING: 'SWARM_AGGREGATING',
  SWARM_COMPLETED: 'SWARM_COMPLETED',
  SWARM_FAILED: 'SWARM_FAILED',
  SWARM_CANCELLED: 'SWARM_CANCELLED',
  CAPABILITY_REGISTERED: 'CAPABILITY_REGISTERED',
  CAPABILITY_ENABLED: 'CAPABILITY_ENABLED',
  CAPABILITY_DISABLED: 'CAPABILITY_DISABLED',
  PROJECT_CAPABILITIES_DISCOVERED: 'PROJECT_CAPABILITIES_DISCOVERED',
  PROJECT_CAPABILITY_CONFIG_INVALID: 'PROJECT_CAPABILITY_CONFIG_INVALID',
  MCP_CONFIG_LOADED: 'MCP_CONFIG_LOADED',
  MCP_CONFIG_RELOADED: 'MCP_CONFIG_RELOADED',
  MCP_SERVER_STARTED: 'MCP_SERVER_STARTED',
  MCP_SERVER_STOPPED: 'MCP_SERVER_STOPPED',
  MCP_SERVER_FAILED: 'MCP_SERVER_FAILED',
  SKILL_DISCOVERED: 'SKILL_DISCOVERED',
  SKILL_RELOADED: 'SKILL_RELOADED',
  SKILL_LOAD_FAILED: 'SKILL_LOAD_FAILED',
  SKILL_RESOLVED: 'SKILL_RESOLVED',
  SKILL_REJECTED: 'SKILL_REJECTED',
  EXTERNAL_TOOL_STARTED: 'EXTERNAL_TOOL_STARTED',
  EXTERNAL_TOOL_COMPLETED: 'EXTERNAL_TOOL_COMPLETED',
  EXTERNAL_TOOL_FAILED: 'EXTERNAL_TOOL_FAILED',
  CONTEXT_COMPACTION_STARTED: 'CONTEXT_COMPACTION_STARTED',
  CONTEXT_COMPACTION_COMPLETED: 'CONTEXT_COMPACTION_COMPLETED',
  CHANGE_CONFLICT_CREATED: 'CHANGE_CONFLICT_CREATED',
  CHANGE_CONFLICT_RESOLUTION_STARTED: 'CHANGE_CONFLICT_RESOLUTION_STARTED',
  CHANGE_CONFLICT_HUNK_RESOLVED: 'CHANGE_CONFLICT_HUNK_RESOLVED',
  CHANGE_CONFLICT_RESOLUTION_COMPLETED: 'CHANGE_CONFLICT_RESOLUTION_COMPLETED',
  CHANGE_CONFLICT_RESOLUTION_REJECTED: 'CHANGE_CONFLICT_RESOLUTION_REJECTED',
  REPOSITORY_INDEX_STARTED: 'REPOSITORY_INDEX_STARTED',
  REPOSITORY_INDEX_PROGRESS: 'REPOSITORY_INDEX_PROGRESS',
  REPOSITORY_INDEX_COMPLETED: 'REPOSITORY_INDEX_COMPLETED',
  REPOSITORY_INDEX_FAILED: 'REPOSITORY_INDEX_FAILED',
  REPOSITORY_INDEX_UPDATED: 'REPOSITORY_INDEX_UPDATED',
  IMPACT_ANALYSIS_STARTED: 'IMPACT_ANALYSIS_STARTED',
  IMPACT_ANALYSIS_PROGRESS: 'IMPACT_ANALYSIS_PROGRESS',
  IMPACT_ANALYSIS_COMPLETED: 'IMPACT_ANALYSIS_COMPLETED',
  IMPACT_ANALYSIS_FAILED: 'IMPACT_ANALYSIS_FAILED',
  REFACTOR_PLAN_CREATED: 'REFACTOR_PLAN_CREATED',
  REFACTOR_PLAN_APPROVAL_REQUIRED: 'REFACTOR_PLAN_APPROVAL_REQUIRED',
  REFACTOR_PLAN_APPROVED: 'REFACTOR_PLAN_APPROVED',
  REFACTOR_PLAN_REJECTED: 'REFACTOR_PLAN_REJECTED',
  REFACTOR_EXECUTION_STARTED: 'REFACTOR_EXECUTION_STARTED',
  REFACTOR_TASK_STARTED: 'REFACTOR_TASK_STARTED',
  REFACTOR_TASK_COMPLETED: 'REFACTOR_TASK_COMPLETED',
  REFACTOR_SCOPE_DRIFT: 'REFACTOR_SCOPE_DRIFT',
  REFACTOR_CONSOLIDATING: 'REFACTOR_CONSOLIDATING',
  REFACTOR_VERIFYING: 'REFACTOR_VERIFYING',
  REFACTOR_REPAIR_REQUIRED: 'REFACTOR_REPAIR_REQUIRED',
  REFACTOR_COMPLETED: 'REFACTOR_COMPLETED',
  REFACTOR_FAILED: 'REFACTOR_FAILED',
  REFACTOR_CANCELLED: 'REFACTOR_CANCELLED',
  HARNESS_ERROR: 'HARNESS_ERROR',
  DIAGNOSTIC_DETECTED: 'DIAGNOSTIC_DETECTED',
  DIAGNOSTIC_SELECTED: 'DIAGNOSTIC_SELECTED',
  DIAGNOSTIC_SENT_TO_AGENT: 'DIAGNOSTIC_SENT_TO_AGENT',
  TEST_VERIFICATION_STATUS: 'ai:test-verification-status',
});

const CONFLICT_TYPE = Object.freeze({
  FILE_CONFLICT: 'FILE_CONFLICT',
  BASELINE_CONFLICT: 'BASELINE_CONFLICT',
  DEPENDENCY_CONFLICT: 'DEPENDENCY_CONFLICT',
  POLICY_CONFLICT: 'POLICY_CONFLICT',
});

const CONFLICT_STATUS = Object.freeze({
  UNRESOLVED: 'UNRESOLVED',
  AUTO_RESOLVED: 'AUTO_RESOLVED',
  MANUAL_REQUIRED: 'MANUAL_REQUIRED',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
});

const HUNK_STATUS = Object.freeze({
  UNCHANGED: 'UNCHANGED',
  PARENT_ONLY: 'PARENT_ONLY',
  INCOMING_ONLY: 'INCOMING_ONLY',
  AUTO_MERGED: 'AUTO_MERGED',
  CONFLICT: 'CONFLICT',
});

const HUNK_RESOLUTION = Object.freeze({
  KEEP_PARENT: 'KEEP_PARENT',
  KEEP_INCOMING: 'KEEP_INCOMING',
  KEEP_BOTH: 'KEEP_BOTH',
  EDIT_RESULT: 'EDIT_RESULT',
});

const DEFAULT_PROJECT_CAPABILITY_LIMITS = Object.freeze({
  maxServers: 50,
  maxSkills: 100,
  maxSkillFileBytes: 1024 * 1024, // 1MB
  maxArgsLength: 100,
  maxTotalArgsChars: 10000,
  maxDescriptionChars: 2000,
  maxInstructionsChars: 50000,
});

const CAPABILITY_TYPE = Object.freeze({
  NEXUS_TOOL: 'NEXUS_TOOL',
  MCP_TOOL: 'MCP_TOOL',
  SKILL: 'SKILL',
});

const CAPABILITY_RISK_LEVEL = Object.freeze({
  SAFE: 'SAFE',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  HIGH_RISK: 'HIGH_RISK',
  BLOCKED: 'BLOCKED',
});

const CAPABILITY_POLICY = CAPABILITY_RISK_LEVEL;

const MCP_SERVER_STATUS = Object.freeze({
  REGISTERED: 'REGISTERED',
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  STOPPED: 'STOPPED',
  FAILED: 'FAILED',
});

const MCP_TRANSPORT = Object.freeze({
  STDIO: 'stdio',
  SSE: 'sse',
  IN_PROCESS: 'in_process',
});

const MCP_CONNECTION_STATUS = Object.freeze({
  CONNECTING: 'CONNECTING',
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  FAILED: 'FAILED',
});

const SKILL_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  INVALID: 'INVALID',
  STALE: 'STALE',
});

const SKILL_SCOPE = Object.freeze({
  BUILTIN: 'BUILTIN',
  PROJECT: 'PROJECT',
  SUBAGENT: 'SUBAGENT',
});

const SWARM_STATUS = Object.freeze({
  PLANNING: 'PLANNING',
  RUNNING: 'RUNNING',
  AGGREGATING: 'AGGREGATING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  PARTIAL_SUCCESS: 'PARTIAL_SUCCESS',
});

const SWARM_TASK_STATUS = Object.freeze({
  PENDING: 'PENDING',
  QUEUED: 'QUEUED',
  RUNNING: 'RUNNING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  SKIPPED: 'SKIPPED',
});

const SWARM_FAILURE_POLICY = Object.freeze({
  FAIL_FAST: 'FAIL_FAST',
  BEST_EFFORT: 'BEST_EFFORT',
});

const SWARM_CONFLICT_CATEGORY = Object.freeze({
  NO_CONFLICT: 'NO_CONFLICT',
  FILE_CONFLICT: 'FILE_CONFLICT',
  BASELINE_CONFLICT: 'BASELINE_CONFLICT',
  DEPENDENCY_CONFLICT: 'DEPENDENCY_CONFLICT',
  POLICY_CONFLICT: 'POLICY_CONFLICT',
});

const DEFAULT_SWARM_LIMITS = Object.freeze({
  maxConcurrentTasks: 3,
  maxTasksPerSwarm: 10,
  taskTimeoutMs: 300000,
  swarmTimeoutMs: 600000,
});


const WORKER_STATUS = Object.freeze({
  IDLE: 'IDLE',
  STARTING: 'STARTING',
  RUNNING: 'RUNNING',
  WAITING_FOR_APPROVAL: 'WAITING_FOR_APPROVAL',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  TERMINATED: 'TERMINATED',
});

const WORKER_TYPE = Object.freeze({
  PROCESS: 'process',
  THREAD: 'thread',
});

const WORKER_MESSAGE_TYPES = Object.freeze({
  START_TURN: 'START_TURN',
  CANCEL_TURN: 'CANCEL_TURN',
  APPROVE_ACTION: 'APPROVE_ACTION',
  REJECT_ACTION: 'REJECT_ACTION',
  PING: 'PING',
  PONG: 'PONG',
  SHUTDOWN: 'SHUTDOWN',
});

const DEFAULT_WORKER_LIMITS = Object.freeze({
  maxConcurrentWorkers: 3,
  workerStartupTimeoutMs: 10000,
  workerIdleTimeoutMs: 300000,
  workerCancellationTimeoutMs: 3000,
  maxWorkerLifetimeMs: 600000,
  maxOutputPayloadBytes: 1024 * 1024,
});

const WORKSPACE_CLEANUP_POLICY = Object.freeze({
  KEEP: 'KEEP',
  DELETE_ON_COMPLETION: 'DELETE_ON_COMPLETION',
  DELETE_ON_PARENT_COMPLETION: 'DELETE_ON_PARENT_COMPLETION',
  DELETE_ON_FAILURE: 'DELETE_ON_FAILURE',
});


const WORKSPACE_STATUS = Object.freeze({
  CREATING: 'CREATING',
  READY: 'READY',
  ADOPTED: 'ADOPTED',
  CLEANED: 'CLEANED',
  FAILED: 'FAILED',
});

const WORKSPACE_ISOLATION_MODE = Object.freeze({
  NONE: 'none',
  GIT_WORKTREE: 'git_worktree',
  SHADOW_COPY: 'shadow_copy',
});

const DEFAULT_SUBAGENT_LIMITS = Object.freeze({
  maxChildDepth: 3,
  maxChildrenPerThread: 10,
  maxTotalChildrenPerTurn: 5,
  maxConcurrentChildren: 3,
  maxChildTurns: 5,
});

/**
 * Generates an immutable, non-array-index unique identifier.
 * @param {string} prefix 
 * @returns {string}
 */
function generateId(prefix = 'id') {
  const ts = Date.now();
  const rand = crypto.randomBytes(4).toString('hex');
  return `${prefix}_${ts}_${rand}`;
}

function generateThreadId() {
  return generateId('thread');
}

function generateTurnId() {
  return generateId('turn');
}

function generateItemId() {
  return generateId('item');
}

function generateEventId() {
  return generateId('evt');
}

function generateChangeSetId() {
  return generateId('cs');
}

function generateHandoffId() {
  return generateId('handoff');
}

function generateWorkspaceId() {
  return generateId('ws_iso');
}

function generateWorkerId() {
  return generateId('worker');
}

function generateSwarmId() {
  return generateId('swarm');
}

function generateSwarmTaskId() {
  return generateId('swtask');
}

function generateCapabilityId() {
  return generateId('cap');
}

function generateMCPServerId() {
  return generateId('mcpsrv');
}

function generateSkillId() {
  return generateId('skill');
}

const SYMBOL_KIND = Object.freeze({
  FUNCTION: 'FUNCTION',
  METHOD: 'METHOD',
  CLASS: 'CLASS',
  INTERFACE: 'INTERFACE',
  TYPE: 'TYPE',
  VARIABLE: 'VARIABLE',
  CONSTANT: 'CONSTANT',
  ENUM: 'ENUM',
  IMPORT: 'IMPORT',
  EXPORT: 'EXPORT',
  MODULE: 'MODULE',
});

const RELATIONSHIP_TYPE = Object.freeze({
  DEFINES: 'DEFINES',
  CONTAINS: 'CONTAINS',
  IMPORTS: 'IMPORTS',
  EXPORTS: 'EXPORTS',
  CALLS: 'CALLS',
  REFERENCES: 'REFERENCES',
  EXTENDS: 'EXTENDS',
  IMPLEMENTS: 'IMPLEMENTS',
  TYPE_REFERENCES: 'TYPE_REFERENCES',
});

const IMPACT_CONFIDENCE = Object.freeze({
  DIRECT: 'DIRECT',
  STRUCTURAL: 'STRUCTURAL',
  HEURISTIC: 'HEURISTIC',
});

const IMPACT_CATEGORY = Object.freeze({
  DIRECT_CALLER: 'DIRECT_CALLER',
  TRANSITIVE_CALLER: 'TRANSITIVE_CALLER',
  IMPORT_DEPENDENT: 'IMPORT_DEPENDENT',
  EXPORT_DEPENDENT: 'EXPORT_DEPENDENT',
  TYPE_DEPENDENT: 'TYPE_DEPENDENT',
  IMPLEMENTATION_DEPENDENT: 'IMPLEMENTATION_DEPENDENT',
  TEST_DEPENDENT: 'TEST_DEPENDENT',
  POTENTIAL_REFERENCE: 'POTENTIAL_REFERENCE',
  HEURISTIC_MATCH: 'HEURISTIC_MATCH',
});

const REFACTOR_PLAN_STATUS = Object.freeze({
  ANALYSIS: 'ANALYSIS',
  PROPOSED: 'PROPOSED',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  APPROVED: 'APPROVED',
  EXECUTING: 'EXECUTING',
  CONSOLIDATING: 'CONSOLIDATING',
  VERIFYING: 'VERIFYING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

function generateConflictId() {
  return generateId('conflict');
}

function generateSymbolId() {
  return generateId('sym');
}

function generateRefactorPlanId() {
  return generateId('plan_refactor');
}

module.exports = {
  THREAD_STATUS,
  TURN_STATUS,
  ITEM_STATUS,
  ITEM_TYPES,
  CHANGESET_STATUS,
  HANDOFF_STATUS,
  WORKSPACE_CLEANUP_POLICY,
  WORKSPACE_STATUS,
  WORKSPACE_ISOLATION_MODE,
  WORKER_STATUS,
  WORKER_TYPE,
  WORKER_MESSAGE_TYPES,
  DEFAULT_WORKER_LIMITS,
  SWARM_STATUS,
  SWARM_TASK_STATUS,
  SWARM_FAILURE_POLICY,
  SWARM_CONFLICT_CATEGORY,
  DEFAULT_SWARM_LIMITS,
  CAPABILITY_TYPE,
  CAPABILITY_RISK_LEVEL,
  CAPABILITY_POLICY,
  MCP_SERVER_STATUS,
  MCP_TRANSPORT,
  MCP_CONNECTION_STATUS,
  SKILL_STATUS,
  SKILL_SCOPE,
  EVENT_TYPES,
  DEFAULT_SUBAGENT_LIMITS,
  DEFAULT_PROJECT_CAPABILITY_LIMITS,
  CONFLICT_TYPE,
  CONFLICT_STATUS,
  HUNK_STATUS,
  HUNK_RESOLUTION,
  SYMBOL_KIND,
  RELATIONSHIP_TYPE,
  IMPACT_CONFIDENCE,
  IMPACT_CATEGORY,
  REFACTOR_PLAN_STATUS,
  generateId,
  generateThreadId,
  generateTurnId,
  generateItemId,
  generateEventId,
  generateChangeSetId,
  generateHandoffId,
  generateWorkspaceId,
  generateWorkerId,
  generateSwarmId,
  generateSwarmTaskId,
  generateCapabilityId,
  generateMCPServerId,
  generateSkillId,
  generateConflictId,
  generateSymbolId,
  generateRefactorPlanId,
};
