const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openFolder: () => ipcRenderer.invoke('dialog:open-folder'),
  getDefaultDemoWorkspace: () => ipcRenderer.invoke('engine:get-default-demo-workspace'),
  readDir: (dirPath) => ipcRenderer.invoke('fs:read-dir', dirPath),
  readFile: (filePath) => ipcRenderer.invoke('fs:read-file', filePath),
  writeFile: (filePath, content) => ipcRenderer.invoke('fs:write-file', filePath, content),
  createFile: (filePath, content, workspacePath, overwrite) => ipcRenderer.invoke('fs:create-file', { filePath, content, workspacePath, overwrite }),
  createDir: (dirPath, workspacePath) => ipcRenderer.invoke('fs:create-dir', { dirPath, workspacePath }),
  deleteFile: (targetPath, workspacePath, recursive) => ipcRenderer.invoke('fs:delete-file', { targetPath, workspacePath, recursive }),
  renameFile: (oldPath, newPath, workspacePath, overwrite) => ipcRenderer.invoke('fs:rename-file', { oldPath, newPath, workspacePath, overwrite }),
  revealInFinder: (targetPath) => ipcRenderer.invoke('fs:reveal-in-finder', targetPath),
  watchWorkspace: (workspacePath) => ipcRenderer.invoke('fs:watch-workspace', workspacePath),
  onFsChanged: (callback) => {
    const listener = (_, arg) => callback(arg);
    ipcRenderer.on('fs:changed', listener);
    return () => ipcRenderer.removeListener('fs:changed', listener);
  },
  fs: {
    readDir: (dirPath) => ipcRenderer.invoke('fs:read-dir', dirPath),
    readFile: (filePath) => ipcRenderer.invoke('fs:read-file', filePath),
    writeFile: (filePath, content) => ipcRenderer.invoke('fs:write-file', filePath, content),
    createFile: (filePath, content, workspacePath, overwrite) => ipcRenderer.invoke('fs:create-file', { filePath, content, workspacePath, overwrite }),
    createDir: (dirPath, workspacePath) => ipcRenderer.invoke('fs:create-dir', { dirPath, workspacePath }),
    deleteFile: (targetPath, workspacePath, recursive) => ipcRenderer.invoke('fs:delete-file', { targetPath, workspacePath, recursive }),
    renameFile: (oldPath, newPath, workspacePath, overwrite) => ipcRenderer.invoke('fs:rename-file', { oldPath, newPath, workspacePath, overwrite }),
    revealInFinder: (targetPath) => ipcRenderer.invoke('fs:reveal-in-finder', targetPath),
    watchWorkspace: (workspacePath) => ipcRenderer.invoke('fs:watch-workspace', workspacePath),
    onFsChanged: (callback) => {
      const listener = (_, arg) => callback(arg);
      ipcRenderer.on('fs:changed', listener);
      return () => ipcRenderer.removeListener('fs:changed', listener);
    },
  },
  parseDiagnostics: (payload) => ipcRenderer.invoke('diagnostics:parse', payload),
  diagnostics: {
    parse: (payload) => ipcRenderer.invoke('diagnostics:parse', payload),
  },
  fileExists: (filePath) => ipcRenderer.invoke('fs:file-exists', filePath),
  analyzeFile: (payload) => ipcRenderer.invoke('engine:analyze', payload),
  previewSafeRemove: (filePath) => ipcRenderer.invoke('engine:preview-safe-remove', filePath),
  applySafeRemove: (filePath, transformedContent) => ipcRenderer.invoke('engine:apply-safe-remove', filePath, transformedContent),
  restoreBackup: (filePath) => ipcRenderer.invoke('engine:restore-backup', filePath),
  scanWorkspace: (workspacePath) => ipcRenderer.invoke('engine:scan-workspace', workspacePath),
  verifyEquivalence: (filePath, transformedContent) => ipcRenderer.invoke('engine:verify-equivalence', filePath, transformedContent),
  buildWorkspaceGraph: (workspacePath) => ipcRenderer.invoke('engine:build-workspace-graph', workspacePath),
  loadWorkspaceState: () => ipcRenderer.invoke('state:load'),
  saveWorkspaceState: (state) => ipcRenderer.invoke('state:save', state),
  exportWorkspaceReport: (payload) => ipcRenderer.invoke('report:export', payload),
  previewSurgery: (payload) => ipcRenderer.invoke('surgery:preview', payload),
  applySurgery: (payload) => ipcRenderer.invoke('surgery:apply', payload),
  undoSurgery: (payload) => ipcRenderer.invoke('surgery:undo', payload),
  verifySurgery: (payload) => ipcRenderer.invoke('surgery:verify', payload),
  searchWorkspace: (payload) => ipcRenderer.invoke('workspace:search', payload),
  detectClones: (workspacePath) => ipcRenderer.invoke('engine:detect-clones', workspacePath),
  scanStructuralClones: (workspacePath) => ipcRenderer.invoke('clone:scan', workspacePath),
  detectSemanticClones: (workspacePath) => ipcRenderer.invoke('engine:detect-semantic-clones', workspacePath),
  scanSemanticClones: (workspacePath) => ipcRenderer.invoke('semantic:scan', workspacePath),
  calculateLuminance: (workspacePath) => ipcRenderer.invoke('engine:calculate-luminance', workspacePath),
  listHistory: () => ipcRenderer.invoke('history:list'),
  getHistory: (id) => ipcRenderer.invoke('history:get', id),
  restoreHistory: (id) => ipcRenderer.invoke('history:restore', id),
  appendHistory: (entry) => ipcRenderer.invoke('history:append', entry),
  exportPldiReport: (workspacePath) => ipcRenderer.invoke('report:export-pldi', workspacePath),
  generateFingerprint: (filePath) => ipcRenderer.invoke('behavior:fingerprint', filePath),
  compareFingerprints: (fingerprintA, fingerprintB) => ipcRenderer.invoke('behavior:compare-fingerprints', { fingerprint_a: fingerprintA, fingerprint_b: fingerprintB }),
  analyzeBehaviorHistory: (payload) => ipcRenderer.invoke('behavior:history', payload),
  calculateImpactRadius: (payload) => ipcRenderer.invoke('behavior:impact-radius', payload),
  calculatePropagationTimeline: (payload) => ipcRenderer.invoke('behavior:propagation-timeline', payload),
  calculateBlastRadius: (payload) => ipcRenderer.invoke('behavior:blast-radius', payload),
  runCounterfactualAnalysis: (payload) => ipcRenderer.invoke('behavior:counterfactual', payload),
  evaluatePatchFirewall: (payload) => ipcRenderer.invoke('behavior:patch-firewall', payload),
  evaluateRepositoryFirewall: (payload) => ipcRenderer.invoke('behavior:repository-firewall', payload),
  analyzeSemanticIntentDrift: (payload) => ipcRenderer.invoke('behavior:semantic-intent-drift', payload),
  getBDGGraph: (workspacePath) => ipcRenderer.invoke('bdg:getGraph', workspacePath),
  queryBDGSymbolDependencies: (symbol, relPath, line, workspacePath, targetNodeId) => ipcRenderer.invoke('bdg:querySymbolDependencies', { symbol, relPath, line, workspacePath, targetNodeId }),
  updateBDGFile: (fullPath, content) => ipcRenderer.invoke('bdg:updateFile', { fullPath, content }),
  calculateBDGBlastRadius: (symbol, relPath, line, workspacePath, targetNodeId) => ipcRenderer.invoke('bdg:calculateBlastRadius', { symbol, relPath, line, workspacePath, targetNodeId }),
  analyzeMultiFileImpact: (symbol, relPath, line, workspacePath, targetNodeId) => ipcRenderer.invoke('bdg:analyzeMultiFileImpact', { symbol, relPath, line, workspacePath, targetNodeId }),
  getRuntimeTelemetry: (nodeId) => ipcRenderer.invoke('runtime:getTelemetry', nodeId),
  getRuntimeCallChainComparison: (nodeId) => ipcRenderer.invoke('runtime:getCallChainComparison', nodeId),
  getRuntimeSessions: () => ipcRenderer.invoke('runtime:getSessions'),
  recordRuntimeEvent: (event) => ipcRenderer.invoke('runtime:recordEvent', event),
  correlateRuntimeEvidence: (symbol, relPath, line, workspacePath, targetNodeId) => ipcRenderer.invoke('runtime:correlateEvidence', { symbol, relPath, line, workspacePath, targetNodeId }),
  simulateBDGWhatIf: (symbol, relPath, line, operation, secondarySymbol, targetNodeId) => ipcRenderer.invoke('bdg:simulateWhatIf', { symbol, relPath, line, operation, secondarySymbol, targetNodeId }),
  getBDGBehavioralDiff: (workspacePath) => ipcRenderer.invoke('bdg:getBehavioralDiff', workspacePath),
  generateAIReasoningProposal: (symbol, relPath, line, goal, targetNodeId) => ipcRenderer.invoke('ai:generateProposal', { symbol, relPath, line, goal, targetNodeId }),
  applyAIMutationProposal: (proposalId, approved) => ipcRenderer.invoke('ai:applyProposal', { proposalId, approved }),
  terminal: {
    create: (options) => ipcRenderer.invoke('terminal:create', options),
    write: (id, data) => ipcRenderer.invoke('terminal:write', { id, data }),
    resize: (id, cols, rows) => ipcRenderer.invoke('terminal:resize', { id, cols, rows }),
    kill: (id) => ipcRenderer.invoke('terminal:kill', id),
    restart: (id) => ipcRenderer.invoke('terminal:restart', id),
    list: () => ipcRenderer.invoke('terminal:list'),
    rename: (id, name) => ipcRenderer.invoke('terminal:rename', { id, name }),
    getBuffer: (id) => ipcRenderer.invoke('terminal:getBuffer', id),
    clear: (id) => ipcRenderer.invoke('terminal:clear', id),
    onData: (callback) => {
      const listener = (event, arg) => callback(arg);
      ipcRenderer.on('terminal:data', listener);
      return () => ipcRenderer.removeListener('terminal:data', listener);
    },
    onExit: (callback) => {
      const listener = (event, arg) => callback(arg);
      ipcRenderer.on('terminal:exit', listener);
      return () => ipcRenderer.removeListener('terminal:exit', listener);
    },
    onStatus: (callback) => {
      const listener = (event, arg) => callback(arg);
      ipcRenderer.on('terminal:status', listener);
      return () => ipcRenderer.removeListener('terminal:status', listener);
    },
  },
  git: {
    status: (workspacePath) => ipcRenderer.invoke('git:status', workspacePath),
    diff: (workspacePath, file, staged) => ipcRenderer.invoke('git:diff', { workspacePath, file, staged }),
    stage: (workspacePath, file) => ipcRenderer.invoke('git:stage', { workspacePath, file }),
    unstage: (workspacePath, file) => ipcRenderer.invoke('git:unstage', { workspacePath, file }),
    stageAll: (workspacePath) => ipcRenderer.invoke('git:stageAll', workspacePath),
    unstageAll: (workspacePath) => ipcRenderer.invoke('git:unstageAll', workspacePath),
    commit: (workspacePath, message) => ipcRenderer.invoke('git:commit', { workspacePath, message }),
    fetch: (workspacePath, remote) => ipcRenderer.invoke('git:fetch', { workspacePath, remote }),
    pull: (workspacePath, remote, branch) => ipcRenderer.invoke('git:pull', { workspacePath, remote, branch }),
    push: (workspacePath, remote, branch) => ipcRenderer.invoke('git:push', { workspacePath, remote, branch }),
    sync: (workspacePath, remote, branch) => ipcRenderer.invoke('git:sync', { workspacePath, remote, branch }),
    commitAndPush: (workspacePath, message) => ipcRenderer.invoke('git:commitAndPush', { workspacePath, message }),
    suggestCommitMessage: (workspacePath) => ipcRenderer.invoke('git:suggestCommitMessage', workspacePath),
    branches: (workspacePath) => ipcRenderer.invoke('git:branches', workspacePath),
    checkout: (workspacePath, branch, options) => ipcRenderer.invoke('git:checkout', { workspacePath, branch, ...(typeof options === 'object' ? options : { force: Boolean(options) }) }),
    createBranch: (workspacePath, branch, checkout) => ipcRenderer.invoke('git:createBranch', { workspacePath, branch, checkout }),
    validateBranchName: (name) => ipcRenderer.invoke('git:validateBranchName', { name }),
    stashes: (workspacePath) => ipcRenderer.invoke('git:stashes', workspacePath),
    stashSave: (workspacePath, options) => ipcRenderer.invoke('git:stashSave', { workspacePath, ...(typeof options === 'string' ? { message: options } : (options || {})) }),
    stashApply: (workspacePath, stashId) => ipcRenderer.invoke('git:stashApply', { workspacePath, stashId }),
    stashPop: (workspacePath, stashId) => ipcRenderer.invoke('git:stashPop', { workspacePath, stashId }),
    stashDrop: (workspacePath, stashId) => ipcRenderer.invoke('git:stashDrop', { workspacePath, stashId }),
    stashClear: (workspacePath) => ipcRenderer.invoke('git:stashClear', workspacePath),
    history: (workspacePath, options) => ipcRenderer.invoke('git:history', { workspacePath, options }),
    commitDetails: (workspacePath, hash) => ipcRenderer.invoke('git:commitDetails', { workspacePath, hash }),
    commitDiff: (workspacePath, hash, file, parentIndex) => ipcRenderer.invoke('git:commitDiff', { workspacePath, hash, file, parentIndex }),
    fileHistory: (workspacePath, filePath, options) => ipcRenderer.invoke('git:fileHistory', { workspacePath, filePath, options }),
    discard: (workspacePath, file) => ipcRenderer.invoke('git:discard', { workspacePath, file }),
    // Milestone 33: Git Gutter & Hunk Revert
    getFileHunks: (workspacePath, filePath) => ipcRenderer.invoke('git:getFileHunks', { workspacePath, filePath }),
    revertHunk: (workspacePath, payload) => ipcRenderer.invoke('git:revertHunk', { workspacePath, payload }),
  },
  github: {
    configStatus: () => ipcRenderer.invoke('github:configStatus'),
    status: () => ipcRenderer.invoke('github:status'),
    connect: () => ipcRenderer.invoke('github:connect'),
    disconnect: () => ipcRenderer.invoke('github:disconnect'),
    listRepos: () => ipcRenderer.invoke('github:listRepos'),
    associateRepo: (payload) => ipcRenderer.invoke('github:associateRepo', payload),
    getSelectedRepo: (workspacePath) => ipcRenderer.invoke('github:getSelectedRepo', workspacePath),
    resolveLocalPath: (payload) => ipcRenderer.invoke('github:resolveLocalPath', payload),
    selectCloneDestination: (defaultName) => ipcRenderer.invoke('github:selectCloneDestination', defaultName),
    cloneRepo: (payload) => ipcRenderer.invoke('github:cloneRepo', payload),
  },
  search: {
    run: (payload) => ipcRenderer.invoke('search:run', payload),
    previewReplace: (payload) => ipcRenderer.invoke('search:previewReplace', payload),
    generateChangeSet: (payload) => ipcRenderer.invoke('search:generateChangeSet', payload),
    applyReplace: (payload) => ipcRenderer.invoke('search:applyReplace', payload),
    replace: (payload) => ipcRenderer.invoke('search:replace', payload),
    replaceAll: (payload) => ipcRenderer.invoke('search:replaceAll', payload),
    cancel: (id) => ipcRenderer.invoke('search:cancel', id),
  },
  ai: {
    codeAction: (payload) => ipcRenderer.invoke('ai:code-action', payload),
    getConfig: () => ipcRenderer.invoke('ai:get-config'),
    setConfig: (providerId, modelId) => ipcRenderer.invoke('ai:set-config', { providerId, modelId }),
    setApiKey: (providerId, apiKey) => ipcRenderer.invoke('ai:set-api-key', { providerId, apiKey }),
    removeApiKey: (providerId) => ipcRenderer.invoke('ai:remove-api-key', providerId),
    validateKey: (providerId, apiKey) => ipcRenderer.invoke('ai:validate-key', { providerId, apiKey }),
    getDiagnostics: (providerId) => ipcRenderer.invoke('ai:get-diagnostics', providerId),
    discoverModels: (providerId) => ipcRenderer.invoke('ai:discover-models', providerId),
    hasProviderApiKey: (providerId) => ipcRenderer.invoke('ai:has-api-key', providerId),
    setProviderApiKey: (providerId, apiKey) => ipcRenderer.invoke('ai:set-api-key', { providerId, apiKey }),
    removeProviderApiKey: (providerId) => ipcRenderer.invoke('ai:remove-api-key', providerId),
    discoverProviderModels: (providerId) => ipcRenderer.invoke('ai:discover-models', providerId),
    getProviderDiagnostics: (providerId) => ipcRenderer.invoke('ai:get-diagnostics', providerId),
    setActiveProviderModel: (providerId, modelId) => ipcRenderer.invoke('ai:set-config', { providerId, modelId }),
    onConfigChange: (callback) => {
      const handler = (_event, config) => callback(config);
      ipcRenderer.on('ai:config-changed', handler);
      return () => {
        ipcRenderer.removeListener('ai:config-changed', handler);
      };
    },
    roles: {
      getConfig: () => ipcRenderer.invoke('ai:roles:get-config'),
      setConfig: (roleId, providerId, modelId) => ipcRenderer.invoke('ai:roles:set-config', { roleId, providerId, modelId }),
      resolve: (roleId, sessionConfig) => ipcRenderer.invoke('ai:roles:resolve', { roleId, sessionConfig }),
      validate: (roleId) => ipcRenderer.invoke('ai:roles:validate', roleId),
    },
  },
  evidence: {
    getGraph: (sessionId) => ipcRenderer.invoke('evidence:get-graph', sessionId),
    getSummary: (sessionId) => ipcRenderer.invoke('evidence:get-summary', sessionId),
    traverse: (startId, sessionId, direction) => ipcRenderer.invoke('evidence:traverse', { startId, sessionId, direction }),
  },
  agent: {
    run: (payload) => ipcRenderer.invoke('agent:run', payload),
  },
  patch: {
    applyTransaction: (payload) => ipcRenderer.invoke('patch:apply-transaction', payload),
  },
  recovery: {
    save: (payload) => ipcRenderer.invoke('recovery:save', payload),
    load: (workspacePath) => ipcRenderer.invoke('recovery:load', workspacePath),
    clear: (workspacePath) => ipcRenderer.invoke('recovery:clear', workspacePath),
    list: () => ipcRenderer.invoke('recovery:list'),
    checkCrash: () => ipcRenderer.invoke('recovery:check-crash'),
  },
  continuum: {
    save: (snapshot, workspacePath) => ipcRenderer.invoke('continuum:save', { snapshot, workspacePath }),
    list: (workspacePath) => ipcRenderer.invoke('continuum:list', workspacePath),
    load: (snapshotId, workspacePath) => ipcRenderer.invoke('continuum:load', { snapshotId, workspacePath }),
    delete: (snapshotId, workspacePath) => ipcRenderer.invoke('continuum:delete', { snapshotId, workspacePath }),
    buildContext: (snapshot) => ipcRenderer.invoke('continuum:build-context', snapshot),
    createCurrent: (payload, workspacePath) => ipcRenderer.invoke('continuum:create-current', { payload, workspacePath }),
    resumeSession: (snapshotId, workspacePath) => ipcRenderer.invoke('continuum:resume-session', { snapshotId, workspacePath }),
    getLatest: (workspacePath) => ipcRenderer.invoke('continuum:get-latest', workspacePath),
    generateHandoff: (payload) => ipcRenderer.invoke('continuum:generate-handoff', payload),
    exportCapsule: (payload) => ipcRenderer.invoke('continuum:export-capsule', payload),
    importCapsule: (payload) => ipcRenderer.invoke('continuum:import-capsule', payload),
    openCapsuleDialog: () => ipcRenderer.invoke('dialog:open-capsule-file'),
  },
  harness: {
    createThread: (options) => ipcRenderer.invoke('harness:create-thread', options),
    getThread: (threadId, workspacePath) => ipcRenderer.invoke('harness:get-thread', { threadId, workspacePath }),
    listThreads: (filter) => ipcRenderer.invoke('harness:list-threads', filter),
    pinThread: (threadId, pinned, workspacePath) => ipcRenderer.invoke('harness:pin-thread', { threadId, pinned, workspacePath }),
    renameThread: (threadId, title, workspacePath) => ipcRenderer.invoke('harness:rename-thread', { threadId, title, workspacePath }),
    deleteThread: (threadId, workspacePath) => ipcRenderer.invoke('harness:delete-thread', { threadId, workspacePath }),
    searchThreads: (query, workspacePath) => ipcRenderer.invoke('harness:search-threads', { query, workspacePath }),
    archiveThread: (threadId) => ipcRenderer.invoke('harness:archive-thread', threadId),
    onThreadsChange: (callback) => {
      const handler = (_event, data) => callback(data);
      ipcRenderer.on('harness:threads-changed', handler);
      return () => {
        ipcRenderer.removeListener('harness:threads-changed', handler);
      };
    },
    startTurn: (payload) => ipcRenderer.invoke('harness:start-turn', payload),
    getTurn: (turnId) => ipcRenderer.invoke('harness:get-turn', turnId),
    completeTurn: (payload) => ipcRenderer.invoke('harness:complete-turn', payload),
    failTurn: (payload) => ipcRenderer.invoke('harness:fail-turn', payload),
    cancelTurn: (payload) => ipcRenderer.invoke('harness:cancel-turn', payload),
    runTurn: (payload) => ipcRenderer.invoke('harness:run-turn', payload),
    approveAction: (payload) => ipcRenderer.invoke('harness:approve-action', payload),
    rejectAction: (payload) => ipcRenderer.invoke('harness:reject-action', payload),
    routeRequest: (payload) => ipcRenderer.invoke('harness:route-request', payload),
    handleRequest: (payload) => ipcRenderer.invoke('harness:handle-request', payload),
    startItem: (payload) => ipcRenderer.invoke('harness:start-item', payload),
    updateItem: (payload) => ipcRenderer.invoke('harness:update-item', payload),
    completeItem: (payload) => ipcRenderer.invoke('harness:complete-item', payload),
    failItem: (payload) => ipcRenderer.invoke('harness:fail-item', payload),
    getEvents: (filter) => ipcRenderer.invoke('harness:get-events', filter),
    cancelSwarm: (swarmId, reason) => ipcRenderer.invoke('harness:cancel-swarm', { swarmId, reason }),
    getSwarmStatus: (swarmId) => ipcRenderer.invoke('harness:get-swarm-status', swarmId),
    discoverProjectCapabilities: (workspacePath) => ipcRenderer.invoke('harness:discover-project-capabilities', workspacePath),
    loadProjectCapabilities: (payload) => ipcRenderer.invoke('harness:load-project-capabilities', payload),
    reloadProjectCapabilities: (payload) => ipcRenderer.invoke('harness:reload-project-capabilities', payload),
    getProjectMetadata: (workspacePath) => ipcRenderer.invoke('harness:get-project-metadata', workspacePath),
    getCapabilities: () => ipcRenderer.invoke('harness:get-capabilities'),
    getCapability: (id) => ipcRenderer.invoke('harness:get-capability', id),
    getMCPServers: () => ipcRenderer.invoke('harness:get-mcp-servers'),
    getMCPServerStatus: (serverId) => ipcRenderer.invoke('harness:get-mcp-server-status', serverId),
    getMCPServerTools: (serverId) => ipcRenderer.invoke('harness:get-mcp-server-tools', serverId),
    getSkills: () => ipcRenderer.invoke('harness:get-skills'),
    getSkill: (skillId) => ipcRenderer.invoke('harness:get-skill', skillId),
    getProjectCapabilityStatus: (workspacePath) => ipcRenderer.invoke('harness:get-project-capability-status', workspacePath),
    startMCPServer: (serverId) => ipcRenderer.invoke('harness:start-mcp-server', serverId),
    stopMCPServer: (serverId) => ipcRenderer.invoke('harness:stop-mcp-server', serverId),
    restartMCPServer: (serverId) => ipcRenderer.invoke('harness:restart-mcp-server', serverId),
    enableSkill: (skillId) => ipcRenderer.invoke('harness:enable-skill', skillId),
    disableSkill: (skillId) => ipcRenderer.invoke('harness:disable-skill', skillId),
    listChangeConflicts: () => ipcRenderer.invoke('harness:list-change-conflicts'),
    getChangeConflict: (conflictId) => ipcRenderer.invoke('harness:get-change-conflict', conflictId),
    resolveConflictHunk: (payload) => ipcRenderer.invoke('harness:resolve-conflict-hunk', payload),
    resolveFileConflict: (payload) => ipcRenderer.invoke('harness:resolve-file-conflict', payload),
    createParentChangeSetFromConflicts: (payload) => ipcRenderer.invoke('harness:create-parent-changeset-from-conflicts', payload),
    applyResolvedConflicts: (payload) => ipcRenderer.invoke('harness:apply-resolved-conflicts', payload),
    cancelConflictResolution: (payload) => ipcRenderer.invoke('harness:cancel-conflict-resolution', payload),
    // Language Intelligence & Problems (Milestone 31 & 32)
    getDefinition: (query) => ipcRenderer.invoke('harness:get-definition', query),
    findReferences: (query) => ipcRenderer.invoke('harness:find-references', query),
    getHover: (query) => ipcRenderer.invoke('harness:get-hover', query),
    prepareRename: (query) => ipcRenderer.invoke('harness:prepare-rename', query),
    applyRename: (options) => ipcRenderer.invoke('harness:apply-rename', options),
    getDocumentOutline: (query) => ipcRenderer.invoke('harness:get-document-outline', query),
    getSymbolAtPosition: (query) => ipcRenderer.invoke('harness:get-symbol-at-position', query),
    getBreadcrumbs: (query) => ipcRenderer.invoke('harness:get-breadcrumbs', query),
    parseDiagnostics: (payload) => ipcRenderer.invoke('harness:parse-diagnostics', payload),
    getProblems: (filter) => ipcRenderer.invoke('harness:get-problems', filter),
    addProblems: (payload) => ipcRenderer.invoke('harness:add-problems', payload),
    clearProblems: (filter) => ipcRenderer.invoke('harness:clear-problems', filter),
    getProblemsSummary: () => ipcRenderer.invoke('harness:get-problems-summary'),
    onEvent: (callback) => {
      const listener = (_, event) => callback(event);
      ipcRenderer.on('harness:event', listener);
      return () => ipcRenderer.removeListener('harness:event', listener);
    },
  },
  testing: {
    detect: (workspacePath) => ipcRenderer.invoke('testing:detect', workspacePath),
    run: (payload) => ipcRenderer.invoke('testing:run', payload),
    cancel: (runId) => ipcRenderer.invoke('testing:cancel', runId),
  },
  autonomous: {
    start: (payload) => ipcRenderer.invoke('autonomous:start', payload),
    cancel: (repairId) => ipcRenderer.invoke('autonomous:cancel', repairId),
    getStatus: (repairId) => ipcRenderer.invoke('autonomous:get-status', repairId),
    onProgress: (callback) => {
      const listener = (_, data) => callback(data);
      ipcRenderer.on('autonomous:progress', listener);
      return () => ipcRenderer.removeListener('autonomous:progress', listener);
    },
  },
  tests: {
    discover: (workspacePath) => ipcRenderer.invoke('test:discover', workspacePath),
    run: (payload) => ipcRenderer.invoke('test:run', payload),
    runFile: (payload) => ipcRenderer.invoke('test:run-file', payload),
    runAll: (payload) => ipcRenderer.invoke('test:run-all', payload),
    coverage: (payload) => ipcRenderer.invoke('test:coverage', payload),
    debugTest: (payload) => ipcRenderer.invoke('test:debug', payload),
  },
  debug: {
    createSession: (options) => ipcRenderer.invoke('debug:createSession', options),
    getSession: (sessionId) => ipcRenderer.invoke('debug:getSession', sessionId),
    launch: (payload) => ipcRenderer.invoke('debug:launch', payload),
    pause: (sessionId) => ipcRenderer.invoke('debug:pause', sessionId),
    continue: (sessionId) => ipcRenderer.invoke('debug:continue', sessionId),
    stepOver: (sessionId) => ipcRenderer.invoke('debug:stepOver', sessionId),
    stepInto: (sessionId) => ipcRenderer.invoke('debug:stepInto', sessionId),
    stepOut: (sessionId) => ipcRenderer.invoke('debug:stepOut', sessionId),
    stop: (sessionId) => ipcRenderer.invoke('debug:stop', sessionId),
    setBreakpoints: (payload) => ipcRenderer.invoke('debug:setBreakpoints', payload),
    getBreakpoints: (payload) => ipcRenderer.invoke('debug:getBreakpoints', payload),
    addWatchExpression: (payload) => ipcRenderer.invoke('debug:addWatchExpression', payload),
    removeWatchExpression: (payload) => ipcRenderer.invoke('debug:removeWatchExpression', payload),
    evaluate: (payload) => ipcRenderer.invoke('debug:evaluate', payload),
    debugTest: (payload) => ipcRenderer.invoke('debug:debugTest', payload),
  },
  settings: {
    get: (workspacePath) => ipcRenderer.invoke('settings:get', workspacePath),
    update: (payload) => ipcRenderer.invoke('settings:update', payload),
    reset: (payload) => ipcRenderer.invoke('settings:reset', payload),
    resetAll: (payload) => ipcRenderer.invoke('settings:resetAll', payload),
  },
  keybindings: {
    get: () => ipcRenderer.invoke('keybindings:get'),
    update: (payload) => ipcRenderer.invoke('keybindings:update', payload),
    reset: (payload) => ipcRenderer.invoke('keybindings:reset', payload),
    resetAll: () => ipcRenderer.invoke('keybindings:resetAll'),
    detectConflicts: (list) => ipcRenderer.invoke('keybindings:detectConflicts', list),
  },
  profiler: {
    python: (payload) => ipcRenderer.invoke('profiler:python', payload),
    javascript: (payload) => ipcRenderer.invoke('profiler:javascript', payload),
    memory: (payload) => ipcRenderer.invoke('profiler:memory', payload),
    react: (payload) => ipcRenderer.invoke('profiler:react', payload),
    export: (payload) => ipcRenderer.invoke('profiler:export', payload),
  },
  security: {
    scan: (workspacePath) => ipcRenderer.invoke('security:scan', workspacePath),
    export: (payload) => ipcRenderer.invoke('security:export', payload),
  },
  snapshots: {
    create: (payload) => ipcRenderer.invoke('snapshot:create', payload),
    list: (workspacePath) => ipcRenderer.invoke('snapshot:list', workspacePath),
    get: (payload) => ipcRenderer.invoke('snapshot:get', payload),
    compare: (payload) => ipcRenderer.invoke('snapshot:compare', payload),
    restoreFile: (payload) => ipcRenderer.invoke('snapshot:restore-file', payload),
    restoreWorkspace: (payload) => ipcRenderer.invoke('snapshot:restore-workspace', payload),
    delete: (payload) => ipcRenderer.invoke('snapshot:delete', payload),
  },
  hardening: {
    checkHealth: () => ipcRenderer.invoke('health:check'),
    reportCrash: (error, context) => ipcRenderer.invoke('crash:report', { error, context }),
    listCrashes: () => ipcRenderer.invoke('crash:list'),
    log: (level, category, message, meta) => ipcRenderer.invoke('logger:log', { level, category, message, meta }),
    getRecentLogs: (limit) => ipcRenderer.invoke('logger:recent', limit),
    getTelemetry: () => ipcRenderer.invoke('telemetry:get'),
    setTelemetry: (enabled) => ipcRenderer.invoke('telemetry:set', enabled),
    trackTelemetry: (eventName) => ipcRenderer.invoke('telemetry:track', eventName),
  },
  capsule: {
    createCapsule: (threadId, options) => ipcRenderer.invoke('capsule:create', { threadId, options }),
    loadCapsule: (capsuleId) => ipcRenderer.invoke('capsule:load', capsuleId),
    listCapsules: () => ipcRenderer.invoke('capsule:list'),
    resolveReference: (ref) => ipcRenderer.invoke('capsule:resolve-reference', ref),
    deleteCapsule: (capsuleId) => ipcRenderer.invoke('capsule:delete', capsuleId),
    openCapsuleDialog: () => ipcRenderer.invoke('capsule:open-dialog'),
    parseCapsule: (raw) => ipcRenderer.invoke('capsule:parse', raw),
    validateCapsule: (capsule) => ipcRenderer.invoke('capsule:validate', capsule),
    generateContinuationPrompt: (capsule) => ipcRenderer.invoke('capsule:generate-continuation-prompt', capsule),
    importCapsuleFile: (filePath) => ipcRenderer.invoke('capsule:import-file', filePath),
    evaluateBudget: (threadId) => ipcRenderer.invoke('capsule:evaluate-budget', threadId),
  },
  intelligence: {
    preflightEstimate: (payload) => ipcRenderer.invoke('intelligence:preflight-estimate', payload),
    getEvidence: (sessionId) => ipcRenderer.invoke('intelligence:get-evidence', { sessionId }),
    correlateBreakage: (payload) => ipcRenderer.invoke('intelligence:correlate-breakage', payload),
    getDecisions: (payload) => ipcRenderer.invoke('intelligence:get-decisions', payload),
    recordDecision: (payload) => ipcRenderer.invoke('intelligence:record-decision', payload),
    confirmDecision: (payload) => ipcRenderer.invoke('intelligence:confirm-decision', payload),
    rejectDecision: (payload) => ipcRenderer.invoke('intelligence:reject-decision', payload),
    replayDecision: (payload) => ipcRenderer.invoke('intelligence:replay-decision', payload),
    searchDecisions: (payload) => ipcRenderer.invoke('intelligence:search-decisions', payload),
    detectDecisions: (payload) => ipcRenderer.invoke('intelligence:detect-decisions', payload),
    simulateBug: (payload) => ipcRenderer.invoke('intelligence:simulate-bug', payload),
    getScenarioPresets: () => ipcRenderer.invoke('intelligence:get-scenario-presets'),
    inspectDeployment: (payload) => ipcRenderer.invoke('intelligence:inspect-deployment', payload),
    generateDeploymentConfig: (payload) => ipcRenderer.invoke('intelligence:generate-deployment-config', payload),
    applyDeploymentConfig: (payload) => ipcRenderer.invoke('intelligence:apply-deployment-config', payload),
    // Deployment Credentials & Execution (Phase 3A)
    getProviderAuthStatus: (providerId) => ipcRenderer.invoke('intelligence:get-provider-auth-status', { providerId }),
    saveProviderCredential: (payload) => ipcRenderer.invoke('intelligence:save-provider-credential', payload),
    removeProviderCredential: (providerId) => ipcRenderer.invoke('intelligence:remove-provider-credential', { providerId }),
    startDeployment: (payload) => ipcRenderer.invoke('intelligence:start-deployment', payload),
    cancelDeployment: (deploymentId) => ipcRenderer.invoke('intelligence:cancel-deployment', { deploymentId }),
    onDeploymentLogChunk: (callback) => {
      const listener = (_event, payload) => callback(payload);
      ipcRenderer.on('deployment:log-chunk', listener);
      return () => ipcRenderer.removeListener('deployment:log-chunk', listener);
    },
    onDeploymentState: (callback) => {
      const listener = (_event, payload) => callback(payload);
      ipcRenderer.on('deployment:state-change', listener);
      return () => ipcRenderer.removeListener('deployment:state-change', listener);
    },
  },

  runPythonFile: (filePath) => ipcRenderer.invoke('python:run-file', filePath),
  onPythonOutput: (callback) => {
    const listener = (_event, payload) => callback(payload);
    ipcRenderer.on('python:output', listener);
    return () => ipcRenderer.removeListener('python:output', listener);
  },
});


